package com.fabiocompany.supermercadosdeltaplus.model;
// Generated 24/09/2017 15:11:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

/**
 * Detalleoferta generated by hbm2java
 */

@Entity
//@MappedSuperclass
@Table(name="detalleoferta")
public class Detalleoferta implements java.io.Serializable {

    //@EmbeddedId
    //@AttributeOverride(name="iddetalleoferta", column = @Column(name="iddetalleoferta"))
    @Id
    @Column(name="iddetalleoferta")
	@GeneratedValue(strategy=GenerationType.AUTO)
    private int iddetalleoferta;
    
    @Column(name="montodedescuento")
    private double montodedescuento;
    
    @Column(name="descripciondepromocion")
    private String descripciondepromocion;
     
    @ManyToMany(cascade = {CascadeType.ALL},mappedBy="detalleofertas")
    private Set<Detalleticket> detalletickets = new HashSet(0);

    public Detalleoferta() {
    }

	
    public Detalleoferta(int iddetalleoferta) {
        this.iddetalleoferta = iddetalleoferta;
    }
    public Detalleoferta(int iddetalleoferta, Double montodedescuento, String descripciondepromocion, Set<Detalleticket> detalletickets) {
       this.iddetalleoferta = iddetalleoferta;
       this.montodedescuento = montodedescuento;
       this.descripciondepromocion = descripciondepromocion;
       this.detalletickets = detalletickets;
    }
   
    public int getIddetalleoferta() {
        return this.iddetalleoferta;
    }
    
    public void setIddetalleoferta(int iddetalleoferta) {
        this.iddetalleoferta = iddetalleoferta;
    }
    public Double getMontodedescuento() {
        return this.montodedescuento;
    }
    
    public void setMontodedescuento(Double montodedescuento) {
        this.montodedescuento = montodedescuento;
    }
    public String getDescripciondepromocion() {
        return this.descripciondepromocion;
    }
    
    public void setDescripciondepromocion(String descripciondepromocion) {
        this.descripciondepromocion = descripciondepromocion;
    }
    public Set getDetalletickets() {
        return this.detalletickets;
    }
    
    public void setDetalletickets(Set<Detalleticket> detalletickets) {
        this.detalletickets = detalletickets;
    }

    @Override
    public int hashCode() {
        return getIddetalleoferta();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Detalleoferta other = (Detalleoferta) obj;
        if (this.getIddetalleoferta() != other.getIddetalleoferta()) {
            return false;
        }
        return true;
    }



}


