package com.fabiocompany.supermercadosdeltaplus.model;
// Generated 24/09/2017 15:11:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Detalleticket generated by hbm2java
 */
//@MappedSuperclass
@Entity
@Table(name="detalleticket")
public class Detalleticket  implements java.io.Serializable {

    //@EmbeddedId
    //@AttributeOverride(name="iddetalleticket", column = @Column(name="iddetalleticket"))
    @Id
    @Column(name="iddetalleticket")
	@GeneratedValue(strategy=GenerationType.AUTO)
    private int iddetalleticket;
     
    @ManyToOne
    @JoinColumn(name="idticket")  
    private Cabeceraticket cabeceraticket;
    
    
    @OneToOne(cascade=CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Pago pago;
 
    @Column(name="cantidad")
    private int cantidad;
    
    @Column(name="subtotal")
    private double subtotal;
    
    @Column(name="total")
    private double total;
    
    @Column(name="cantidadporproducto")
    private int cantidadporproducto;
    
    @ManyToMany(cascade = {CascadeType.ALL})
	@JoinTable(name="ticketsyofertas", joinColumns = {
            @JoinColumn(name = "iddetalleticket") }, inverseJoinColumns = {
		@JoinColumn(name = "iddetalleoferta") })
    private Set<Detalleofertaypromocion> detalleofertas = new HashSet(0);
    
    @ManyToMany(cascade = {CascadeType.ALL})
	@JoinTable(name="ticketsyproductos", joinColumns = {
            @JoinColumn(name = "iddetalleticket") }, inverseJoinColumns = {
		@JoinColumn(name = "idproducto") })
    private Set<Producto> productos = new HashSet(0);


    public Detalleticket() {
    }
    
    public Detalleticket(int iddetalleticket, Cabeceraticket cabeceraticket, Pago pago,
			int cantidad, double subtotal, double total, int cantidadporproducto, Set<Detalleofertaypromocion> detalleofertas,
			Set<Producto> productos) {
		this.iddetalleticket = iddetalleticket;
		this.cabeceraticket = cabeceraticket;
		this.pago = pago;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
		this.total = total;
		this.cantidadporproducto = cantidadporproducto;
		this.detalleofertas = detalleofertas;
		this.productos = productos;
	}



	public int getIddetalleticket() {
		return iddetalleticket;
	}



	public void setIddetalleticket(int iddetalleticket) {
		this.iddetalleticket = iddetalleticket;
	}



	public Cabeceraticket getCabeceraticket() {
		return cabeceraticket;
	}



	public void setCabeceraticket(Cabeceraticket cabeceraticket) {
		this.cabeceraticket = cabeceraticket;
	}


	public Pago getPago() {
		return pago;
	}



	public void setPago(Pago pago) {
		this.pago = pago;
	}



	public int getCantidad() {
		return cantidad;
	}



	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}



	public double getSubtotal() {
		return subtotal;
	}



	public void setSubtotal(double subtotal) {
		this.subtotal = subtotal;
	}



	public double getTotal() {
		return total;
	}



	public void setTotal(double total) {
		this.total = total;
	}



	public int getCantidadporproducto() {
		return cantidadporproducto;
	}



	public void setCantidadporproducto(int cantidadporproducto) {
		this.cantidadporproducto = cantidadporproducto;
	}



	public Set<Detalleofertaypromocion> getDetalleofertas() {
		return detalleofertas;
	}



	public void setDetalleofertas(Set<Detalleofertaypromocion> detalleofertas) {
		this.detalleofertas = detalleofertas;
	}



	public Set<Producto> getProductos() {
		return productos;
	}



	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}



	@Override
    public int hashCode() {
        return getIddetalleticket();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Detalleticket other = (Detalleticket) obj;
        if (this.getIddetalleticket() != other.getIddetalleticket()) {
            return false;
        }
        return true;
    }



}


