package com.fabiocompany.supermercadosdeltaplus.model;
// Generated 24/09/2017 15:11:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.IndexColumn;
import org.hibernate.annotations.Proxy;

/**
 * Personausuario generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Access(value = AccessType.FIELD)
@Table(name="personausuario")
public class Personausuario implements java.io.Serializable {
   
	@Id
    @Column(name="idpersonausuario")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private int idpersonausuario;
    
    @Column(name="dnipersonausuario")
    private String dnipersonausuario;
    
    @Column(name="nombrepersonausuario")
    private String nombrepersonausuario;
    
    @Column(name="numerodetelefono")
    private String numerodetelefono;
    
    @Column(name="correo")
    private String correo;
    
    public Personausuario() {
    }

    public Personausuario(int idpersonausuario, String dnipersonausuario, String nombrepersonausuario, String numerodetelefono, String correo) {
       this.idpersonausuario = idpersonausuario;
       this.dnipersonausuario = dnipersonausuario;
       this.nombrepersonausuario = nombrepersonausuario;
       this.numerodetelefono = numerodetelefono;
       this.correo = correo;
    }
   
    public String getDnipersonausuario() {
        return this.dnipersonausuario;
    }
    
    public void setDnipersonausuario(String dnipersonausuario) {
        this.dnipersonausuario = dnipersonausuario;
    }
    
    public void setIdpersonausuario(int idpersonausuario){
        this.idpersonausuario = idpersonausuario;
    }
    
    public int getIdpersonausuario() {
        return this.idpersonausuario;
    }
    public String getNombrepersonausuario() {
        return this.nombrepersonausuario;
    }
    
    public void setNombrepersonausuario(String nombrepersonausuario) {
        this.nombrepersonausuario = nombrepersonausuario;
    }
    public String getNumerodetelefono() {
        return this.numerodetelefono;
    }
    
    public void setNumerodetelefono(String numerodetelefono) {
        this.numerodetelefono = numerodetelefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    @Override
    public int hashCode() {
        return getIdpersonausuario();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Personausuario other = (Personausuario) obj;
        if (this.getIdpersonausuario() != other.getIdpersonausuario()) {
            return false;
        }
        return true;
    }

	@Override
	public String toString() {
		return "Personausuario [idpersonausuario=" + idpersonausuario + ", dnipersonausuario=" + dnipersonausuario
				+ ", nombrepersonausuario=" + nombrepersonausuario + ", numerodetelefono=" + numerodetelefono
				+ ", correo=" + correo + "]";
	}

}


