package com.fabiocompany.supermercadosdeltaplus.model;
// Generated 24/09/2017 15:11:33 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
//@MappedSuperclass
@Table(name="tarjeta")
public class Tarjeta  implements java.io.Serializable {
	//@EmbeddedId
    //@AttributeOverride(name="numtarjeta", column = @Column(name="numtarjeta"))
    @Id
    @Column(name="idtarjeta")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private int idtarjeta;

    
    @Column(name="numtarjeta")
    private String numtarjeta;
    
    @ManyToOne
    @JoinColumn(name="idtipodepago")
    private Tipodepago tipodepago;
    
    @Column(name="nombretarjeta")
    private String nombretarjeta;

    public Tarjeta() {
    }

    public Tarjeta(int idtarjeta, String numtarjeta, Tipodepago tipodepago, String nombretarjeta) {
       this.idtarjeta = idtarjeta;
       this.numtarjeta = numtarjeta;
       this.tipodepago = tipodepago;
       this.nombretarjeta = nombretarjeta;
    }
       
    public int getIdtarjeta() {
	return idtarjeta;
    }

    public void setIdtarjeta(int idtarjeta) {
	this.idtarjeta = idtarjeta;
    }

    public String getNumtarjeta() {
        return this.numtarjeta;
    }
    
    public void setNumtarjeta(String numtarjeta) {
        this.numtarjeta = numtarjeta;
    }
    public Tipodepago getTipodepago() {
        return this.tipodepago;
    }
    
    public void setTipodepago(Tipodepago tipodepago) {
        this.tipodepago = tipodepago;
    }
    public String getNombretarjeta() {
        return this.nombretarjeta;
    }
    
    public void setNombretarjeta(String nombretarjeta) {
        this.nombretarjeta = nombretarjeta;
    }

    @Override
    public int hashCode() {
        return getIdtarjeta();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tarjeta other = (Tarjeta) obj;
        if (this.getIdtarjeta()!= other.getIdtarjeta()) {
            return false;
        }
        return true;
    }
    
}


